name: Assets

on: [push, pull_request]
permissions:
  contents: read

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-versions: ['16', '18', '20']
      fail-fast: false
    name: Node ${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
          cache: 'npm'
          cache-dependency-path: assets/admin/package-lock.json
      - name: "Install dependencies"
        run: npm ci
        working-directory: ./assets/admin
      - name: "Lint"
        run: npm run lint
        working-directory: ./assets/admin
